const { AllUsers, AllWithdrawals, UpdateWithdrawals, CreateAdminWallets, UpdateAdminWallet, DeleteWallet, GetAdminWallets, GetUserFigures, AllInvestments, UpdateInvestments, CreateTradingPlan, GetTradingPlans, UpdateTradingPlan, DeleteTradingPlan, AllDeposits, UpdateDeposits, GetAdminStore, UpdateAdminStore, AllTaxes, UpdateTaxes, AdminCreateAccount, UpdateUsers, UpdateKYC, CreateCryptocurrency, GetCryptocurrency, UpdateCryptocurrency, DeleteCryptocurrency, ReactivateUsers } = require('../controllers/adminControllers')
const { AdminMiddleware } = require('../middleware/auth')


const router = require('express').Router()

router.get('/all-users', AdminMiddleware, AllUsers)
router.get('/all-deposits', AdminMiddleware, AllDeposits)
router.get('/all-investments', AdminMiddleware, AllInvestments)
router.get('/all-withdrawals', AdminMiddleware, AllWithdrawals)
router.get('/all-taxes', AdminMiddleware, AllTaxes)
router.put('/update-deposits', AdminMiddleware, UpdateDeposits)
router.put('/update-investments', AdminMiddleware, UpdateInvestments)
router.put('/update-withdrawals', AdminMiddleware, UpdateWithdrawals)
router.put('/update-taxes', AdminMiddleware, UpdateTaxes)
router.put('/update-kyc', AdminMiddleware, UpdateKYC)
router.put('/update-users', AdminMiddleware, UpdateUsers)
router.put('/reactivate-users', AdminMiddleware, ReactivateUsers)
router.post('/admin-create-account', AdminMiddleware, AdminCreateAccount)
router.post('/get-user-figures', AdminMiddleware, GetUserFigures)
router.post('/create-cryptocurrency', AdminMiddleware, CreateCryptocurrency)
router.get('/all-cryptocurrency', AdminMiddleware, GetCryptocurrency)
router.put('/update-cryptocurrency', AdminMiddleware, UpdateCryptocurrency)
router.post('/delete-cryptocurrency', AdminMiddleware, DeleteCryptocurrency)
router.post('/create-admin-wallet', AdminMiddleware, CreateAdminWallets)
router.get('/all-admin-wallets', AdminMiddleware, GetAdminWallets)
router.put('/update-admin-wallet', AdminMiddleware, UpdateAdminWallet)
router.post('/delete-admin-wallet', AdminMiddleware, DeleteWallet)
router.post('/create-trading-plan', AdminMiddleware, CreateTradingPlan)
router.get('/all-trading-plans', GetTradingPlans)
router.put('/update-trading-plan', AdminMiddleware, UpdateTradingPlan)
router.post('/delete-trading-plan', AdminMiddleware, DeleteTradingPlan)
router.get('/admin-store', GetAdminStore)
router.put('/update-admin-store', AdminMiddleware, UpdateAdminStore)


module.exports = router